#!/bin/bash

printfeild() {
  case "$1" in
    1)
      printf '[\033[31mFailed\033[0m]'
      (( FailCount++ ))
      (( Fail++ ))
      ;;
    0)
      printf '[\033[32mPassed\033[0m]'
      (( PassCount++ ))
      (( Pass++ ))
      ;;
    2)
      printf '[\033[33m Warn \033[0m]'
      (( WarnCount++ ))
      (( Warn++ ))
      ;;
    *)
      printf '[      ]'
      ;;
    esac
  printf ' %-20s : %-20s : %s\n' "$TestProg $TestProgArg" "$2" "$3"
}

IsExaAble() {
  if [ "${TestProg#*/}" = "$TestProg" ]; then
    command -v "$TestProg" >/dev/null 2>&1
  else
    [ -x "$TestProg" ]
  fi
}

CheckOutHex() {
  case "$TestOutHex" in
    48656c6c6f2c20576f726c64210a)
      printfeild 0 "Output" "$(<"$TempDir/stdout")"
      ;;
    48656c6c6f20576f726c64210a|48656c6c6f2c20576f726c6421|48656c6c6f20576f726c6421)
      printfeild 2 "Output" "$(<"$TempDir/stdout")"
      printfeild -1 "Hex" "$TestOutHex"
      ;;
    68656c6c6f20576f726c64210a|656c6c6f20576f726c6421|68656c6c6f20776f726c6421|48656c6c6f20776f726c6421)
      printfeild 2 "Output" "$(<"$TempDir/stdout")"
      printfeild -1 "Hex" "$TestOutHex"
      ;;
    *)
      printfeild 1 "Output" "$(<"$TempDir/stdout")"
      printfeild -1 "Hex" "$TestOutHex"
      printfeild -1 "Expected" "48656c6c6f2c20576f726c64210a"
      ;;
  esac
}

CheckStderr() {
  if [ -s "$TempDir/stderr" ]; then
    StderrHex="$(od -An -tx1 "$TempDir/stderr" | tr -d ' ')"

    case "$StderrHex" in
      0a)
        printfeild 2 "stderr" "\n"
        ;;
      *4d697a756b69*)
        printfeild 0 "stderr" "Mizuki found"
        ;;
      *)
        printfeild 1 "stderr" "NOT EMPTY"
        ;;
    esac
  else
    printfeild 0 "stderr" "Empty"
  fi
}

CheckRuntime() {
  Runtime=$((TestEnd - TestStart))

  if (( Runtime >= 1000000000 )); then
    RuntimeReable="~$(( Runtime / 1000000000 ))s"
  elif (( Runtime >= 1000000 )); then
    RuntimeReable="~$(( Runtime / 1000000 ))ms"
  else
    RuntimeReable="${Runtime}ns"
  fi

  if (( Runtime <= MAX_runtime )); then
    printfeild 0 "Runtime" "$RuntimeReable"
  elif (( Runtime <= MAX_runtime * 15 / 10 )); then
    printfeild 2 "Runtime" "$RuntimeReable"
  else
    printfeild 1 "Runtime" "$RuntimeReable"
  fi
}

ParseTestProg() {
  read -r -a args <<< "$TestProg"

  TestProg="${args[0]}"
  TestProgArg=("${args[@]:1}")
}

TestResult() {
  if (( Fail >= Pass )); then
    printfeild -1 "Result" "Failed"
    (( FailedTest++ ))
  elif (( Fail > 0 )); then
    printfeild -1 "Result" "Passed with errors"
    (( WarnedTest++ ))
  elif (( Warn > 0 )); then
    printfeild -1 "Result" "Passed with warnings"
    (( WarnedTest++ ))
  else
    printfeild -1 "Result" "Passed"
    (( PassedTest++ ))
  fi
}

TestSummary() {
  printf '%*s\n' "$MaxSumLine" '' | tr ' ' '-'

  printf 'Test summary : \n'
  printf "Total \033[32m%-5s\033[0m count : %s\n" "Pass" "$PassCount"
  printf "Total \033[31m%-5s\033[0m count : %s\n" "Fail" "$FailCount"
  printf "Total \033[33m%-5s\033[0m count : %s\n" "Warn" "$WarnCount"
  printf '\n'

  printf '\033[32m%-6s\033[0m test count : %s\n' "Pass" "$PassedTest"
  printf '\033[33m%-6s\033[0m test count : %s\n' "Pass*" "$WarnedTest"
  printf '\033[31m%-6s\033[0m test count : %s\n' "Fail" "$FailedTest"
  printf '\033[90m\033[3m%s\n\033[0m' "* : It didn't fail too \"dramastic\"."

  printf '%*s\n' "$MaxSumLine" '' | tr ' ' '-'
}

main() {
  ParseTestProg

  Warn=0
  Pass=0
  Fail=0

  if ! IsExaAble; then
    printfeild 1 "Executable" "No"
  else
    printfeild 0 "Executable" "Yes"
    
    TestStart=$(date +%s%N)
    (
      timeout "$Runtime_limit" "$TestProg" "${TestProgArg[@]}" \
      2>"$TempDir/stderr" >"$TempDir/stdout"
      exit $?
    ) 2>/dev/null
    TestErrcode=$?
    TestEnd=$(date +%s%N)
    case "$TestErrcode" in
      124)
        printfeild 1 "Runtime" "Timed out"
        return
        ;;
      0)
        printfeild 0 "Errorcode" "$TestErrcode"
        ;;
      139)
        printfeild 1 "Errorcode" "Segfaulted(Mizuki is mad at this)"
        return
        ;;
      *)
        printfeild 1 "Errorcode" "$TestErrcode"
    esac
      
    TestOutHex="$(od -An -tx1 "$TempDir/stdout" | tr -d ' ')"
    CheckOutHex
    
    CheckRuntime      
    CheckStderr

    rm "$TempDir"/*
  fi
}

if [[ -z $MAX_runtime ]]; then
  MAX_runtime=30000000
fi

if [[ -z $Runtime_limit ]]; then
  Runtime_limit=5
fi

if [[ -n $Max_Runtime_ms ]]; then
  MAX_runtime=$((Max_Runtime_ms * 1000000))
  printfeild 2 "Max Runtime" "${MAX_runtime}ns"
  printf '\n'
fi

if [[ -n $Max_Runtime_s ]]; then
  MAX_runtime=$((Max_Runtime_s * 1000000000))
  printfeild 2 "Max Runtime" "${MAX_runtime}ns"
  printf '\n'
fi

FailCount=0
PassCount=0
WarnCount=0

TempDir="$(mktemp -d /tmp/helloworldtest.XXXXXX)"

MaxSumLine=30
FailedTest=0

for TestProg in "$@"; do
  main  
  TestResult
  printf '\n'
done

rm -r "$TempDir"

TestSummary

if (( FailedTest > 0 )); then
  exit 1
else
  exit 0
fi
