#!/bin/bash

array_contains() {
  local needle="$1"
  shift

  for item in "$@"; do
    [[ "$item" == "$needle" ]] && return 0
  done

 return 1
}

array_remove() {
  local -n _array="$1"
  local pattern="$2"
  local i
  local skip=false

  for i in "${!_array[@]}"; do
    if [[ ${_array[i]} == -- ]]; then
      skip=false
        continue
    fi

    if [[ $skip == true ]]; then
        skip=false
        continue
    fi

    if [[ ${_array[i]} == -* ]]; then
      skip=true
      continue
    fi

    [[ ${_array[i]} == $pattern ]] && unset '_array[i]'
  done

  _array=("${_array[@]}")
}

printfeild() {
  case "$1" in
    1)
      printf '[\e[31mFailed\e[0m]'
      (( FailCount++ ))
      (( Fail++ ))
      ;;
    0)
      printf '[\e[32mPassed\e[0m]'
      (( PassCount++ ))
      (( Pass++ ))
      ;;
    2)
      printf '[\e[33m Warn \e[0m]'
      (( WarnCount++ ))
      (( Warn++ ))
      ;;
    3)
      printf '[\e[31mError \e[0m]'
      ;;
    4)
      printf '[\e[33mNotice\e[0m]'
      ;;
    5)
      printf '[\e[36mResult\e[0m]'
      ;;
    *)
      printf '[      ]'
      ;;
    esac
  printf ' %-20s : %-20s : %s\n' "$TestProg $TestProgArg" "$2" "$3"
}

if (( $# == 0 )); then
  TestProg="helloworldtest"
  printfeild 3 "" "No input files"
  exit 127
fi

IsExaAble() {
  if [[ "${TestProg#*/}" == "$TestProg" ]]; then
    command -v "$TestProg" >/dev/null 2>&1
  else
    [ -f "$TestProg" ] && [ -x "$TestProg" ]
  fi
}

ArgParse() {

  TestProg="helloworldtest"

  case "$1" in
    --)
      ArgAllowed=0
      return
      ;;

    -f|--file)
      [[ -n $2 ]] || {
        printfeild 4 "$1" "requires an argument"
        exit 128
      }
    
      if ! array_contains "$2" "${ImportedFiles[@]}"; then
        mapfile -t -O "${#Args[@]}" Args < "$2"

        ImportedFiles+=("$2")
      else
        printfeild 4 "$2" "is imported, not reimporting!"
      fi

      ;;

    -r|--runtime)
      [[ -n $2 ]] || {
        printfeild 4 "$1" "requires an argument"
        exit 128
      }

      case "$2" in
        -*)
          if (( -"$2" >= MAX_runtime )); then
            printfeild 4 "$1" "MAX runtime cannot be 0 or lower"
          else
            (( MAX_runtime += $2 * 1000000000 ))
          fi
          ;;
        +*) (( MAX_runtime += $2 * 1000000000 )) ;;
        *)
          if (( "$2" <= 0 )); then
            printfeild 4 "$1" "MAX runtime cannot be 0 or lower"
          else
            (( MAX_runtime = $2 * 1000000000 ))
          fi
          ;;
      esac

      if (( MAX_runtime >= 1000000000 )); then
        RuntimeReable="~$(( MAX_runtime / 1000000000 ))s"
      elif (( MAX_runtime >= 1000000 )); then
        RuntimeReable="~$(( MAX_runtime / 1000000 ))ms"
      else
        RuntimeReable="${MAX_runtime}ns"
      fi

      printfeild 4 "$1" "Max pass runtime set to ${RuntimeReable}."

      ;;
    -t|--timeout)
      [[ -n $2 ]] || {
        printfeild 4 "$1" "requires an argument"
        exit 128
      }

      case "$2" in
        -*)
          if (( -"$2" >= Runtime_limit )); then
            printfeild 4 "$1" "Runtime limit cannot be 0 or lower."
          else
            (( Runtime_limit += $2))
          fi
          ;;
        +*) (( Runtime_limit += $2 )) ;;
        *)
          if (( "$2" <= 0 )); then
            printfeild 4 "$1" "Runtime_limit cannot be 0 or lower."
          else
            (( Runtime_limit = $2 ))
          fi
          ;;
      esac

      printfeild 4 "$1" "Runtime Limit set to ${Runtime_limit}s."
      ;;
    --is-mizuki-tuff|--is-Mizuki-tuff)
      AkiyamaMizukiIsTuff
      return
      ;;
    -h|--help)
      HelpArticle
      AkiyamaMizukiIsTuff
      exit
      ;;
    -d|--directory)
      [[ -d $2 ]] || {
        printfeild 4 "$1" "requires an argument WHICH IS A DIRECTORY"
        exit 128
      }

      mapfile -d '' -t -O "${#Args[@]}" Args < <(find "$2" -type f -print0)

      ;;

    -e|--exclude)
      [[ -n $2 ]] || {
        printfeild 4 "$1" "requires an argument WHICH IS A PATTERN"
        exit 128
      }
      
      array_remove Args "$2"
      ;;
    *)
      printfeild 3 "$1" "Unknown argument"
      [[ -x $1 ]] && printfeild 4 "$1 might be a program, you would need to use -- for that."
      exit 128
  esac

  (( ArgNum++ ))
  return
}

CheckOutHex() {
  case "$TestOutHex" in
    48656c6c6f2c20576f726c64210a)
      printfeild 0 "Output" "$(<"$TempDir/stdout")"
      ;;
    48656c6c6f20576f726c64210a|48656c6c6f2c20576f726c6421|48656c6c6f20576f726c6421)
      printfeild 2 "Output" "$(<"$TempDir/stdout")"
      printfeild -1 "Hex" "$TestOutHex"
      printfeild -1 "Expected" "48656c6c6f2c20576f726c64210a"
      ;;
    68656c6c6f20576f726c64210a|656c6c6f20576f726c6421|68656c6c6f20776f726c6421|48656c6c6f20776f726c6421)
      printfeild 2 "Output" "$(<"$TempDir/stdout")"
      printfeild -1 "Hex" "$TestOutHex"
      printfeild -1 "Expected" "48656c6c6f2c20576f726c64210a"
      ;;
    *)
      printfeild 1 "Output" "$(<"$TempDir/stdout")"
      printfeild -1 "Hex" "$TestOutHex"
      printfeild -1 "Expected" "48656c6c6f2c20576f726c64210a"
      ;;
  esac
}

CheckStderr() {
  if [ -s "$TempDir/stderr" ]; then
    StderrHex="$(od -An -tx1 "$TempDir/stderr" | tr -d ' ')"

    case "$StderrHex" in
      0a)
        printfeild 2 "stderr" "\n"
        ;;
      *4d697a756b69*)
        printfeild 0 "stderr" "Mizuki found"
        ;;
      *)
        printfeild 1 "stderr" "NOT EMPTY"
        ;;
    esac
  else
    printfeild 0 "stderr" "Empty"
  fi
}

CheckRuntime() {
  Runtime=$((TestEnd - TestStart))

  if (( Runtime >= 1000000000 )); then
    RuntimeReable="~$(( Runtime / 1000000000 ))s"
  elif (( Runtime >= 1000000 )); then
    RuntimeReable="~$(( Runtime / 1000000 ))ms"
  else
    RuntimeReable="${Runtime}ns"
  fi

  if (( Runtime <= MAX_runtime )); then
    printfeild 0 "Runtime" "$RuntimeReable"
  elif (( Runtime <= MAX_runtime * 15 / 10 )); then
    printfeild 2 "Runtime" "$RuntimeReable"
  else
    printfeild 1 "Runtime" "$RuntimeReable"
  fi
}

ParseTestProg() {
  read -r -a args <<< "$TestProg"

  TestProg="${args[0]}"
  TestProgArg=("${args[@]:1}")
}

TestResult() {
  if (( Fail >= Pass )); then
    printfeild 5 "Result" "Failed"
    (( FailedTest++ ))
  elif (( Fail > 0 )); then
    printfeild 5 "Result" "Passed with errors"
    (( WarnedTest++ ))
  elif (( Warn > 0 )); then
    printfeild 5 "Result" "Passed with warnings"
    (( WarnedTest++ ))
  else
    printfeild 5 "Result" "Passed"
    (( PassedTest++ ))
  fi
}

TestSummary() {
  printf '%*s\n' "$MaxSumLine" '' | tr ' ' '-'

  printf 'Test summary : \n'
  printf "Total \033[32m%-5s\033[0m count : %s\n" "Pass" "$PassCount"
  printf "Total \033[31m%-5s\033[0m count : %s\n" "Fail" "$FailCount"
  printf "Total \033[33m%-5s\033[0m count : %s\n" "Warn" "$WarnCount"
  printf '\n'

  printf '\033[32m%-6s\033[0m test count : %s\n' "Pass" "$PassedTest"
  printf '\033[33m%-6s\033[0m test count : %s\n' "Pass*" "$WarnedTest"
  printf '\033[31m%-6s\033[0m test count : %s\n' "Fail" "$FailedTest"
  printf '\033[90m\033[3m%s\n\033[0m' "* : It didn't fail too \"dramastic\"."

  printf '%*s\n' "$MaxSumLine" '' | tr ' ' '-'
}

HelpArticle() {
  TestProg=""

  printf '%-30s : %s\n' "--" "Makes EVERY arguments after this a testing program."
  printf '%-30s : %s\n' "-f|--file [file]" "APPEND [file] to THE END of testing program list."
  printf '%-30s : %s\n' "-r|--runtime (+|-)[value]" "(+|-|set) max acceptable runtime to [value]."
  printf '%-30s : %s\n' "-t|--timeout (+|-)[value]" "(+|-|set) timeout runtime to [value]."
  printf '%-30s : %s\n' "-d|--directory [directory]" "Test every file in [directory]."
  printf '%-30s : %s\n' "-e|--exclude [pattern]" "Execlude every file with pattern [pattern]."
  printf '%-30s : %s\n' "-h|--help" "Show this help."
  printf '\n'
  printf '%-30s : %s\n' "-t|--timeout|-r|--runtime +|- rule" ""
  printf '%-30s : %s\n' '[value]' 'set [value].'
  printf '%-30s : %s\n' '+[value]' 'add [value].'
  printf '%-30s : %s\n' '-[value]' 'minus [value].'
  printf '\n'
  printf '%-30s : %s\n' "-e|--exclude pattern" "Like bash pattern matching."
  printf '\n'
  printf '\033[90m\033[3m%-30s\n\033[0m' "Note : arguments can be stacked and parsed in order."
  printf '\033[90m\033[3m%-30s\n\033[0m' "Note : I'm too lazy to invent regex in bash so i just borrow bash pattern matching."
  printf '\033[90m\033[3m%-30s\n\033[0m' "The end of Hatsune Miku mentioned!"
}

DoTest() {
  ParseTestProg

  Warn=0
  Pass=0
  Fail=0

  if ! IsExaAble; then
    printfeild 1 "Executable" "No"
  else
    printfeild 0 "Executable" "Yes"
    
    TestStart=$(date +%s%N)
    (
      timeout "$Runtime_limit" "$TestProg" "${TestProgArg[@]}" \
      2>"$TempDir/stderr" >"$TempDir/stdout"
      exit $?
    ) 2>/dev/null
    TestErrcode=$?
    TestEnd=$(date +%s%N)
    case "$TestErrcode" in
      124)
        printfeild 1 "Runtime" "Timed out"
        return
        ;;
      0)
        printfeild 0 "Errorcode" "$TestErrcode"
        ;;
      139)
        printfeild 1 "Errorcode" "Segfaulted(Mizuki is mad at this)"
        return
        ;;
      *)
        printfeild 1 "Errorcode" "$TestErrcode"
    esac
      
    TestOutHex="$(od -An -tx1 "$TempDir/stdout" | tr -d ' ')"
    CheckOutHex
    
    CheckRuntime      
    CheckStderr

    rm "$TempDir"/*
  fi
}

AkiyamaMizukiIsTuff() {
  local transBLUE='\e[38;2;91;206;250m'
  local transPINK='\e[38;2;245;169;184m'
  local transWHITE='\e[38;2;255;255;255m'
  local BOLD='\e[1m'
  local UNDERLINE='\e[4m'
  local RESET='\e[0m'
  printf "$UNDERLINE${transBLUE}Aki${transPINK}yama${transWHITE} Mizu${transPINK}ki${RESET} is${transBLUE} $UNDERLINE${BOLD}tuff$RESET\n"
}

Runtime_limitLck=0
Max_RuntimeLck=0

if [[ -z $MAX_runtime ]]; then
  MAX_runtime=30000000
fi

if [[ -n $Max_Runtime_ms ]]; then
  if (( Max_Runtime_ms <= 0 )); then
    printfeild 3 "Max runtime" "cannot be 0 or lower, using default of 30ms (or 0.03s)"
    Max_RuntimeLck=1
  else
    MAX_runtime=$((Max_Runtime_ms * 1000000))
    if ! [[ -n $Max_Runtime_s ]]; then
      printfeild 4 "Max runtime" "${MAX_runtime}ns"
    fi
  fi

  if ! [[ -n $Max_Runtime_s ]]; then
    if [[ -z $Runtime_limit ]]; then
      printf '\n'
    fi
  fi
  
fi

if [[ -n $Max_Runtime_s ]]; then
  if (( Max_Runtime_s <= 0 )); then
    
    if (( Max_RuntimeLck == 0 )); then
      printfeild 3 "Max runtime" "cannot be 0 or lower, using default of 30ms (or 0.03s)"
    fi

    if [[ -z $Runtime_limit ]]; then
      printfeild 3 "Runtime limit" "cannot be 0 or lower, using default of 5s  (or 5000ms)"
      Runtime_limitLck=1
      printf '\n'
    fi
    
  else
    if [[ -n $Max_Runtime_ms ]]; then
      (( MAX_runtime+=Max_Runtime_s * 1000000000 ))
    else
      MAX_runtime=$((Max_Runtime_s * 1000000000))
    fi
    printfeild 4 "Max runtime" "${MAX_runtime}ns"

    if [[ -z $Runtime_limit ]]; then
      Runtime_limit=$(( Max_Runtime_s * 2 ))
      printfeild 4 "Runtime limit" "${Runtime_limit}s"
      Runtime_limitLck=1
      printf '\n'
    fi
  fi 
fi

if [[ -z $Runtime_limit ]]; then
  Runtime_limit=5
else
  if (( Runtime_limit <= 0 )); then
    printfeild 3 "Runtime limit" "cannot be 0 or lower, using default of 5s  (or 5000ms)"
    printf '\n'
    Runtime_limit=5
  else
    if (( Runtime_limitLck == 0 )); then
      printfeild 4 "Runtime limit" "${Runtime_limit}s"
      printf '\n'
    fi
  fi
fi

FailCount=0
PassCount=0
WarnCount=0

TempDir="$(mktemp -d /tmp/helloworldtest.XXXXXX)"

MaxSumLine=30
FailedTest=0
PassedTest=0
WarnedTest=0

Args=("$@")

RunTest() {
  DoTest
  TestResult
  printf '\n'
  return
}

ArgAllowed=1

for ((ArgNum = 0; ArgNum < ${#Args[@]}; ArgNum++)); do
  TestProg="${Args[ArgNum]}"

  if (( ArgAllowed == 1 )); then
    case "$TestProg" in
      -*) ArgParse "${Args[@]:ArgNum:2}" ;;
      *) RunTest ;;
    esac
  else
    RunTest
  fi
done

rm -r "$TempDir"

TestSummary

if (( FailedTest > 126 )); then
  exit 255
elif (( FailedTest > 0 )); then
  exit "$FailedTest"
else
  exit 0
fi
