name: workflow

on: [workflow_dispatch, push]

jobs:
  do_it:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchains
        run: |
          sudo apt update
          sudo apt install -y \
            nodejs \
            python3 \
            gcc \
            g++ \
            golang \
            rustc

      - name: COMPILE
        run: src/build.sh

      - name: Run Tests
        run: ./helloworldtest run/* || true

      - name: Run Tests with options
        run: |
          Max_Runtime_ms=25 ./helloworldtest run/* || true
          Max_Runtime_s=0 ./helloworldtest run/* || true
          Runtime_limit=4 Max_Runtime_ms=20 ./helloworldtest run/* || true 
          Max_Runtime_ms=1 Max_Runtime_s=0 ./helloworldtest run/* || true 
          Runtime_limit=0 Max_Runtime_ms=0 Max_Runtime_s=0 ./helloworldtest run/* || true
      - name: Run Tests with NEWER options
        run : |
          ./helloworldtest -d run -e '*.cpp'; true
          ./helloworldtest -e '*.cpp' run/*; true
          echo '-f' > program.txt; true
          echo 'program.txt' >> program.txt; true
          ./helloworldtest -f program.txt; true
          rm -f program.txt; true
          ./helloworldtest --is-Mizuki-tuff -e 'test.*' run/*; true
          ./helloworldtest -d .; true


